### PR TITLE
Set second-order derivatives to 0 on layer 1 cells.

### PR DESCRIPTION
**Pull request by ykempf**
Fix suggestion to the initial AEA crash.

This is tested at scale with AEA and we are seemingly happy with this. Should this go into master?

### CODE REVIEW

**Comment by galfthan** [comment]
For future reference. This fixed an issue at the inflow boundary where spurious artifacts appeared. See picture on the left hand, compared to the situation on the right after the fix. 
aea_left-old_right-new

The issue appeared as a side-effect of ed9131, runs before this did not experience problems.

**Comment by galfthan** [comment]
Looks good to go into master from my POV. I guess one could still run it through test package just to be pedantic, and "current" reference results should in any case be updated.

**Comment by ykempf** [comment]
My suspicion, based on the fact that the feature disappeared with the Hall term set to 1st order accuracy or turned off altogether, was that these derivatives introduced strongly spatially varying Hall E patterns at the boundaries which triggered issues in combination with the field solver changes done earlier (commit ed9131). In any case, apart for the weak inflowing signature, we're fine now with that.

**Comment by ursg** [comment]
The magnetosphere tests give some small differences in the testpackage (as would be expected). Otherwise the diffs are zero.

```
running Magnetosphere_small 
Parameter data file (sw1.dat) has 1 values
--------------------------------------------------------------------------------------------
Magnetosphere_small  -  Verifying 97fad11004f1a23538d066ef7d7a2847b14e8d16___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER__DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER against current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
206.7        214.1         0.965437
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                10.3971                 1.0163e-05    
rho_v_0                1.29623e+07                 2.59243e-05    
rho_v_1                3.49611e+07                 0.00180191    
rho_v_2                1.75875e+06                 0.00108812    
B_0                8.56728e-13                 0.000214654    
B_1                1.35767e-12                 0.000336684    
B_2                1.48954e-12                 8.93722e-08    
E_0                7.84668e-06                 0.00359422    
E_1                9.21839e-06                 0.00143671    
E_2                3.14645e-06                 0.00176212    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /mnt/btrfs/work/uganse/testpackage/testpackage_data/current/Magnetosphere_small/bulk.0000001.vlsv & /mnt/btrfs/work/uganse/testpackage/run_2017.03.23_16.12.45/Magnetosphere_small/bulk.0000001.vlsv
NonIdenticalBlocks:      1
IdenticalBlocks:         3325
Absolute_Error:          1.23856e-11
Mean-Absolute-Error:     4.98393e-16
Max-Absolute-Error:      1.25755e-13
Absolute-log-Error:      204.836
Mean-Absolute-log-Error: 0.00824255
--------------------------------------------------------------------------------------------
running Magnetosphere_polar_small 
Parameter data file (sw1.dat) has 1 values
--------------------------------------------------------------------------------------------
Magnetosphere_polar_small  -  Verifying 97fad11004f1a23538d066ef7d7a2847b14e8d16___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER__DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER against current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
229.6        227.7         1.00834
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                7.14314                 4.61905e-06    
rho_v_0                1.32403e+07                 1.55341e-05    
rho_v_1                4.06786e+08                 0.538661    
rho_v_2                5.58927e+06                 0.000109648    
B_0                1.46473e-12                 7.24133e-07    
B_1                5.65864e-11                 0.749574    
B_2                5.24948e-13                 9.97279e-10    
E_0                9.41859e-05                 0.802373    
E_1                1.48858e-06                 0.000124231    
E_2                6.6996e-05                 0.734636    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /mnt/btrfs/work/uganse/testpackage/testpackage_data/current/Magnetosphere_polar_small/bulk.0000001.vlsv & /mnt/btrfs/work/uganse/testpackage/run_2017.03.23_16.12.45/Magnetosphere_polar_small/bulk.0000001.vlsv
NonIdenticalBlocks:      40
IdenticalBlocks:         100581
Absolute_Error:          2.19686e-10
Mean-Absolute-Error:     1.61307e-16
Max-Absolute-Error:      2.44254e-13
Absolute-log-Error:      3041.03
Mean-Absolute-log-Error: 0.00223291
--------------------------------------------------------------------------------------------
```

**Comment by ursg** [comment]
Looked at the diffs: they are, as expected, happening at the boundaries, but behaviour looks good.

**Pull request merged**
