### PR TITLE
Issue 322 calculate wave speed skip

### PR DESCRIPTION
**Pull request by ykempf**
Fixing 322, compiles, not tested yet but "what can possibly go wrong"? If @ursg you could provide me with a location with reference data, I can run the test package myself if you prefer.

### CODE REVIEW

**Comment by ykempf** [comment]
Ööh, this of course only includes the last commit as a meaningful change I suppose.

**Comment by ykempf** [comment]
Ööh, this of course only includes the last commit as a meaningful change I suppose. And the line dipole calculation, it seems.

**Comment by ursg** [comment]
Uh, do you want to rebase this so it only contains the relevant commit? What does the line dipole diff contain?

**Comment by ykempf** [comment]
The pdf version of the pencil-and-paper calculations by Sanni.

**Comment by ursg** [comment]
Surprisingly, this gives zero changes with the testpackage, so let's apply it right away!

**Comment by ykempf** [comment]
We just skip useless calculations, no surprise there.

**Pull request merged**
