### PR TITLE
Fix vector dipole limit distance checks

### PR DESCRIPTION
**Pull request by ursg**
This was discovered as part of #579

The vector dipole has some wrong (and anyway probably useless) tests for the range limit in there. This commit corrects them, but should be tested whether it actually is still identical.

### CODE REVIEW

**Comment by markusbattarbee** [comment]
so actually those checks do nothing. We are already within the region `xlimit[0] < r[0] < xlimit[1]` because regions outside that are dealt with earlier, and `r1 >= r[0]` in all situations.

So we could remove them and just leave the check for whether it should calculate a derivative or not.

**Comment by ursg** [comment]
Automatic testpackage output for pull request #617.

Based on commit ee669249d8ce31fbecb827aa8c494567d41fb462.

Process started by user ```uganse``` on host ```turso02.cs.helsinki.fi``` at Mon, 06 Jun 2022 13:41:03 +0300.

:heavy_check_mark: Compilation succeeded with 202 warnings.

:heavy_check_mark: Testpackage ran successfully.

:heavy_check_mark: acctest_2_maxw_500k_100k_20kms_10deg: Zero diffs.
:heavy_check_mark: acctest_3_substeps: Zero diffs.
:heavy_check_mark: transtest_2_maxw_500k_100k_20kms_20x20: Zero diffs.
:heavy_check_mark: acctest_4_helium: Zero diffs.
:heavy_check_mark: acctest_5_proton_antiproton: Zero diffs.
:heavy_check_mark: restart_write: Zero diffs.
:heavy_check_mark: restart_read: Zero diffs.
:heavy_check_mark: Magnetosphere_small: Zero diffs.
:large_orange_diamond: Magnetosphere_polar_small: Nonzero diffs: `proton/vg_v_nonthermal_0` has absolute error 5.82077e-10, relative error 7.27931e-16.
:heavy_check_mark: test_fp_fsolver_only_3D: Zero diffs.
:heavy_check_mark: test_fp_substeps: Zero diffs.
:heavy_check_mark: Flowthrough_trans_periodic: Zero diffs.
:heavy_check_mark: Flowthrough_x_inflow_y_outflow: Zero diffs.
:heavy_check_mark: Flowthrough_x_inflow_y_outflow_acc: Zero diffs.
:large_orange_diamond: Flowthrough_amr: Nonzero diffs: `proton/vg_rho_0` has absolute error 4.94849e-05, relative error 2.29534e-11.

Full testpackage run output is available in `/home/uganse/work/testpackage/testpackage_run_ee669249d8ce31fbecb827aa8c494567d41fb462.log` on host `turso02.cs.helsinki.fi`

**Comment by markusbattarbee** [comment]
strange nonzero there in mp_polar_small but so small that I guess we can just shrug at it.

Since you already merged quite quickly the auto-pr thingy, I'll put the request here: The output should also list the hash/commit we are comparing against. A link would also be cool :)

**Comment by ursg** [comment]
Yup, I agree, I have been seeing random diffs of this magnitude in both Magnetosphere_polar_small and Flowthrough_AMR even in changes that had absolutely *nothing* to do with these two tests, so I suspect they are just particularly sensitive to numerical fluctuations.

That change in the automatic testpackage script is coming up separately then (and I suspect it would also make sense to define an acceptance range for each test).

**Pull request merged**
