### PR TITLE
Revert last commit of #307: Moment derivatives are actually required.

### PR DESCRIPTION
**Pull request by ursg**
Since within the substeps, the moments are being accessed at both RK2
times alternatingly, they need to be computed back and forth.

This *might* cost some performance, or then again it might be
negligible. If it is to costly, they could also be precomputed and
stored.

### CODE REVIEW

**Comment by ursg** [comment]
Looking at testpackage performance, this doesn't seem to have a big impact at all. Some tests actually ran faster (then again, this is a desktop machine).

**Comment by ykempf** [comment]
The communication pattern can be optimised after https://github.com/fmihpc/vlasiator/blob/master/fieldsolver/derivatives.cpp#L413, as the moments won't change (until we *polate them).

**Comment by ykempf** [comment]
As discussed with Urs now, the new scheme will be:
- always recalculate the derivatives of moments during fs subcycling (can be optimised, but would require a doubling of the moment derivative fields);
- communicate the moments only once (new optimisation, they were always communicated when computing the derivatives, along with the PERB communication).

**Comment by ursg** [comment]
Testpackage'd. Runs properly, and is negligibly faster. I suggest merging it.

**Pull request merged**
