### PR TITLE
Field solver Hall term rho interpolation

### PR DESCRIPTION
**Pull request by ykempf**
This implements the Option 2 of #306, namely interpolation of rho to the cell edges for the Hall term components.

### CODE REVIEW

**Comment by ykempf** [comment]
hall_rho

top: this branch.
bottom: yesterday's version (7aedaf834079b14d6aa280b9b4da732434cd97d5)

**Comment by ykempf** [comment]
axes

For reference, here's the coordinate system and the offsets that should be coded correctly.

**Comment by ykempf** [comment]
hall_rho_averaged

Top: rho averaged form the four neighbours.
Bottom: same as plot before (*polated case).

**Comment by ykempf** [comment]
And here came the code.

**Comment by ykempf** [comment]
Magnetosphere_small  -  Verifying 7ad30ca9fef6caef0354fb04e97e8b21de07a7d3___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER ag
ainst current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
37.25        37.25         1
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                25.5944                 2.5018e-05    
rho_v_0                2.17442e+07                 4.34878e-05    
rho_v_1                8.13432e+06                 0.000419242    
rho_v_2                1.65416e+06                 0.00102351    
B_0                3.96016e-13                 9.92225e-05    
B_1                2.0554e-12                 0.000509675    
B_2                8.54772e-13                 5.12863e-08    
E_0                5.25309e-07                 0.000240623    
E_1                1.3907e-06                 0.000216713    
E_2                1.74236e-06                 0.000975776    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /proj/vlasiato/testpackage/current/Magnetosphere_small/bulk.0000001.vlsv & /wrk/project_vlasov/debug_yk/testpackage/run_2017.02.2
4_11.37.38/Magnetosphere_small/bulk.0000001.vlsv
NonIdenticalBlocks:      0
IdenticalBlocks:         3325
Absolute_Error:          1.29794e-11
Mean-Absolute-Error:     5.22267e-16
Max-Absolute-Error:      1.90522e-13
Absolute-log-Error:      206.902
Mean-Absolute-log-Error: 0.00832538
Application 5383031 resources: utime ~0s, stime ~0s, Rss ~5712, inblocks ~20779, outblocks ~33797
--------------------------------------------------------------------------------------------
running Magnetosphere_polar_small 
Parameter data file (sw1.dat) has 1 values
Application 5383033 resources: utime ~3124s, stime ~72s, Rss ~237772, inblocks ~120142, outblocks ~306036
--------------------------------------------------------------------------------------------
Magnetosphere_polar_small  -  Verifying 7ad30ca9fef6caef0354fb04e97e8b21de07a7d3___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AG
NER against current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
44.09        44.86         0.982835
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                3.55565                 2.29922e-06    
rho_v_0                2.46419e+06                 2.8911e-06    
rho_v_1                1.98965e+07                 0.0262757    
rho_v_2                1.43323e+06                 2.8116e-05    
B_0                4.38752e-14                 2.1691e-08    
B_1                2.07692e-12                 0.0275566    
B_2                4.35218e-14                 8.26812e-11    
E_0                9.11074e-07                 0.00777061    
E_1                4.75564e-06                 0.000396886    
E_2                3.80234e-06                 0.0405079    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /proj/vlasiato/testpackage/current/Magnetosphere_polar_small/bulk.0000001.vlsv & /wrk/project_vlasov/debug_yk/testpackage/run_201
7.02.24_11.37.38/Magnetosphere_polar_small/bulk.0000001.vlsv
NonIdenticalBlocks:      17
IdenticalBlocks:         100593
Absolute_Error:          4.92745e-11
Mean-Absolute-Error:     3.61973e-17
Max-Absolute-Error:      1.62449e-13
Absolute-log-Error:      1530.87
Mean-Absolute-log-Error: 0.00112459

**Comment by ykempf** [comment]
This is compared against 2c0abc49a5df5374d09932befb291360cd889343__DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER.
So I think we're good.

**Comment by ursg** [comment]
Looks good indeed. The differences are miniscule, and if anything, are more correct than before, I would suppose.

**Comment by ykempf** [comment]
Minuscule if anything. ;)

**Pull request merged**
