### PR TITLE
Line dipole paper documentation from Sanni.

### PR DESCRIPTION
**Pull request by ykempf**
Here it is! Lo and behold!

Do we want a wiki page on it? If not, can be merged right away.

### CODE REVIEW

**Comment by markusbattarbee** [comment]
No need to keep this pull hanging, I think, but I created an issue for the wiki.

**Comment by ykempf** [comment]
Mister lead developer will take care of this shortly.

**Comment by ursg** [comment]
The cheap way out would be a wiki page that simply links to this pdf.

Or were you thinking of a more proper explanation of what's happening?

**Comment by markusbattarbee** [comment]
At some point someone should document it and perhaps type it out in LaTeX. I might do this quite soon. But let's not leave this hanging.

**Comment by ykempf** [comment]
It also hangs on the wall here.

**Pull request merged**
