### PR TITLE
Marconi support

### PR DESCRIPTION
**Pull request by ursg**
Starting with a makefile, this pull request is supposed to collect all required changes to make vlasiator work properly on marconi.

### CODE REVIEW

**Comment by ursg** [comment]
My .profile on marconi lists the following, in order to build vlasiator:
```
module load intel
module load intelmpi
module load boost
module load env-knl

export VLASIATOR_ARCH=marconi

umask 0007
```

**Comment by ursg** [comment]
In the main Makefile, jemalloc also needs to be disabled (since it doesn't work well on KNL), by commenting out the ```-DUSE_JEMALLOC``` line.

Instead, intel thread building blocks' own malloc is being used, and for it to be properly reacheable in the environment, ```. /cineca/prod/opt/compilers/intel/pe-xe-2017/binary/tbb/bin/tbbvars.sh intel64``` needs to be run. I suppose that should be part of the startup files as well.

**Comment by ursg** [comment]
Our working directory on marconi is ```/marconi_work/Pra14_3521```, where the libraries are also located.

**Comment by ursg** [comment]
In order to run vlasiator, the LD_LIBRARY_PATH needs to point to the correct places (so that our self-built shared libraries can be found):

````
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/work/libraries/phiprof/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/work/libraries/papi/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BOOST_LIB
LD_PRELOAD=$TBBROOT/lib/intel64/gcc4.7/libtbbmalloc_proxy.so.2
````

**Comment by galfthan** [comment]
Also remember to set VEC16F in main Makefile.  Perhaps this, and USE_JEMALLOC could even be relocated to machine specific makefiles in this branch.

This will be a never-ending struggle otherwise between runs on KNL and Xeon

**Comment by ursg** [comment]
This has been merged into, and superseded by pull request #355

**Pull request closed without merging**
