### PR TITLE
Fixed sisu testpackage

### PR DESCRIPTION
**Pull request by ursg**
A bunch of little things were missing here and there.
The most important change in this pull request: for the tests where only a single spatial cell is present, the testpackage runs only using a single MPI task, since otherwise fsgrid aborts the run.

Tested on Sisu and produced new reference data for vlasiator-4.0.

### CODE REVIEW

**Comment by ykempf** [comment]
Once this is integrated I can also help in testing with some branches like #249/#256.

**Comment by ursg** [comment]
This should now work sufficiently well to be useable for testing other branches.

Some tests still don't work properly though:
- acctest_4_helium doesn't have protons, thus doesn't produce any diff values for those. Would have to have a different mechanism to determine which population to compare
- acctest_5_proton_antiproton only compares the protons for the same reason
- Magnetosphere_small crashes with an MPI error on Sisu for me. This will have to be debugged.

Apart from that, the testpackage *with* this pull request works much better than without already. So I suggest merging.

**Comment by ykempf** [comment]
Does this test "correctly" for restarts? The version I was working on didn't do that correctly yet.

**Comment by ursg** [comment]
Now the "restart_read" test finally properly tests it's output. So I assume that means yes.

**Pull request merged**
