### PR TITLE
Field solver stepping improvements

### PR DESCRIPTION
**Pull request by ykempf**
This wraps up the 20161014 comment on #280. As mentioned there, this is still not stable enough but very likely a significant improvement to have in.

### CODE REVIEW

**Comment by ursg** [comment]
Testpackage gives some small changes here and there:

`Magnetosphere_small  -  Verifying a174e64b244f7d1c1bc124478d20bbb96060354e___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER__DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER against current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
329.4        324.9         1.01385
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                308.2                 0.000301246    
rho_v_0                1.10765e+09                 0.00221527    
rho_v_1                1.00087e+09                 0.0502524    
rho_v_2                4.43523e+07                 0.0271217    
B_0                4.98928e-12                 0.00125049    
B_1                6.98041e-12                 0.00173238    
B_2                9.09348e-11                 5.45609e-06    
E_0                0.00010606                 0.0472803    
E_1                0.000192521                 0.030036    
E_2                1.75858e-05                 0.00985303    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /mnt/btrfs/work/uganse/testpackage/testpackage_data/current/Magnetosphere_small/bulk.0000001.vlsv & /mnt/btrfs/work/uganse/testpackage/run_2017.02.07_17.47.50/Magnetosphere_small/bulk.0000001.vlsv
NonIdenticalBlocks:      2
IdenticalBlocks:         3324
Absolute_Error:          1.34963e-10
Mean-Absolute-Error:     5.42086e-15
Max-Absolute-Error:      9.96024e-13
Absolute-log-Error:      330.473
Mean-Absolute-log-Error: 0.0132736
test_fp_fsolver_only_3D  -  Verifying a174e64b244f7d1c1bc124478d20bbb96060354e___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER__DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER against current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
83.23        114.4         0.727535
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                0                 0    
rho_v_0                0                 0    
rho_v_1                0                 0    
rho_v_2                0                 0    
B_0                5.48625e-12                 0.00704637    
B_1                5.48625e-12                 0.00704637    
B_2                5.48625e-12                 0.00704637    
E_0                2.25883e-08                 0.0130222    
E_1                2.25883e-08                 0.0130222    
E_2                2.25883e-08                 0.0130222    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /mnt/btrfs/work/uganse/testpackage/testpackage_data/current/test_fp_fsolver_only_3D/fullf.0000001.vlsv & /mnt/btrfs/work/uganse/testpackage/run_2017.02.07_17.47.50/test_fp_fsolver_only_3D/fullf.0000001.vlsv
NonIdenticalBlocks:      0
IdenticalBlocks:         0
Absolute_Error:          0
Mean-Absolute-Error:     -nan
Max-Absolute-Error:      0
Absolute-log-Error:      0
Mean-Absolute-log-Error: -nan
`

all other test results are identical, so this has not broken anything in any direct way. And if you say it's an improvement, I would say: let's merge this.

**Comment by galfthan** [comment]
I looked at it yesterday with Yann and we agreed it would be good to go, once the commented-away-code is removed, and a code comment added to say why the two RK steps are taken like that.

I'll also reject 280, since it is covered here. I

**Comment by ykempf** [comment]
@ursg can you provide the files, I'd like to do a visual inspection to check the diffs.

**Comment by ykempf** [comment]
@galfthan I now removed the commented section. Is this ok with you?

**Comment by galfthan** [comment]
ok

**Comment by ursg** [comment]
Now that there are also testpackage runs with subcycles (see #311), I also ran a fieldsover-subcycle test, and it's changes are larger (which, I suppose, is unsurprising):

```
running test_fp_substeps 
--------------------------------------------------------------------------------------------
test_fp_substeps  -  Verifying 6dc23c147997203a1932adb6ac116bcfd3ba4ad9___DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER__DACC_SEMILAG_PQM__DTRANS_SEMILAG_PPM__DDP__DDPF__DVEC4D_AGNER against current
--------------------------------------------------------------------------------------------
------------------------------------------------------------
 ref-time     |   new-time       |  speedup                |
------------------------------------------------------------
23.12        32.74         0.70617
------------------------------------------------------------
  variable     |     absolute diff     |     relative diff | 
------------------------------------------------------------
rho_0                0                 0    
rho_v_0                0                 0    
rho_v_1                0                 0    
rho_v_2                0                 0    
B_0                5.10152e-11                 0.0646105    
B_1                5.10152e-11                 0.0646105    
B_2                5.10152e-11                 0.0646105    
E_0                1.86011e-07                 0.104634    
E_1                1.86011e-07                 0.104634    
E_2                1.86011e-07                 0.104634    
--------------------------------------------------------------------------------------------
   Distribution function diff                                                               
--------------------------------------------------------------------------------------------
INFO Reading in two files.
File names: /mnt/btrfs/work/uganse/testpackage/testpackage_data/current/test_fp_substeps/fullf.0000001.vlsv & /mnt/btrfs/work/uganse/testpackage/run_2017.02.21_11.31.29/test_fp_substeps/fullf.0000001.vlsv
NonIdenticalBlocks:      0
IdenticalBlocks:         0
Absolute_Error:          0
Mean-Absolute-Error:     -nan
Max-Absolute-Error:      0
Absolute-log-Error:      0
Mean-Absolute-log-Error: -nan
```

**Comment by ykempf** [comment]
Indeed the new "maxV" calculation replacing the a_,b_,c_ index magic in ldz_electric_field.cpp is more conservative than what we had before and leads to more subcycles than before.

**Comment by ykempf** [comment]
All lines like `maxV = max(maxV, fabs(Vz0) + fabs(Vx0) + vA + vS + vW);` lead to the higher amount of substeps.

This is arguably too conservative. One could take the geometric sum `sqrt(Vx0*Vx0 + Vz0*Vz0)`, for one, and then `max(that+vMS,that+vW)`, where vMS is `sqrt(vA*vA + vS*vS)`.

I will check what it does to Dispersion tomorrow.

**Comment by ykempf** [comment]
master
305_improved_speeds

The top plot is with master, the bottom one is with the changes suggested and committed above. Compare with the last plot in #280.

Master did 4 subcycles, this guy 3, so we might even have saved a bit.

**Comment by galfthan** [comment]
Looks good. Am I reading left-hand correctly in that the fluctuations do not grow to be as strong (more stable)

**Comment by ykempf** [comment]
Ah the cherry-pick appears again, sorry. And somehow I had to refix Dispersoin, probably the previous fix is in #280 but not ported.

**Comment by ykempf** [comment]
Yes this was one of the "symptoms" last summer: without subcycling the waves didn't keep growing, and I was striving to get this again with subcycling.

**Comment by ykempf** [comment]
To be sure I am running these two tests again without subcycles now, results should come in within an hour or so, Sisu is full.

**Comment by ykempf** [comment]
master_no_substeps
305_improved_speeds_no_substeps

**Comment by ykempf** [comment]
Don't ask me why master without subcycles is weird...

**Comment by ursg** [comment]
This does indeed look good now!

**Comment by ykempf** [comment]
So I assume you were happy with my code changes, good.

Should we make this (or similar) Dispersion part of either the small or the large testpackage?

**Comment by ursg** [comment]
I agree it would be a great idea to have a testrun for this, but I have no idea how to quantify the results into a number. Of course, the test (if run) can always just output a relative difference image to the reference data, and as long as it just looks like random noise, things are fine.

**Pull request merged**
