### PR TITLE
Fix carrington and ukko makefile for compilation of dAMR

### PR DESCRIPTION
**Pull request by ursg**
also includes an updated carrington testpackage run script.

### CODE REVIEW

**Comment by markusbattarbee** [comment]
If we're updating the carrington testpackage launcher script, it should indeed have the full `mpirun -mca pml ucx --mca btl ^vader,tcp,openib -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_TLS=rc,sm -x UCX_IB_ADDR_TYPE=ib_global $executable --run_config $configfile` command shebang. In my testing of multi-node runs I saw that at least the ib_global address type fix was required for any sane performance.

**Comment by markusbattarbee** [comment]
If it now runs, I'm good with this as soon as you get one testpackage run to complete with expected (i.e. ~zero) diffs!

**Comment by ursg** [comment]
Automatic testpackage output for pull request #676.

Based on commit ad7155c8cfef9ec0194701dd105084a14cfbccc6.

Process started by user ```uganse``` on host ```turso01.cs.helsinki.fi``` at Wed, 07 Dec 2022 09:43:35 +0200.

:heavy_check_mark: Compilation succeeded with 29 warnings.

:heavy_check_mark: Testpackage ran successfully.

:heavy_check_mark: acctest_2_maxw_500k_100k_20kms_10deg: Zero diffs.
:heavy_check_mark: acctest_3_substeps: Zero diffs.
:heavy_check_mark: transtest_2_maxw_500k_100k_20kms_20x20: Zero diffs.
:heavy_check_mark: acctest_4_helium: Zero diffs.
:heavy_check_mark: acctest_5_proton_antiproton: Zero diffs.
:large_orange_diamond: restart_write: Nonzero diffs: `fg_e_1` has absolute error 0.0001577, relative error 0.31542.
:large_orange_diamond: restart_read: Nonzero diffs: `fg_e_1` has absolute error 0.000165064, relative error 0.327342.
:large_orange_diamond: Magnetosphere_small: Nonzero diffs: `proton/vg_v_0` has absolute error 31013.9, relative error 0.0615045.
:red_circle: Magnetosphere_polar_small: Failed to run or died with an error.
:heavy_check_mark: test_fp_fsolver_only_3D: Zero diffs.
:heavy_check_mark: test_fp_substeps: Zero diffs.
:heavy_check_mark: Flowthrough_trans_periodic: Zero diffs.
:large_orange_diamond: Flowthrough_x_inflow_y_outflow: Nonzero diffs: `fg_e_1` has absolute error 0.0001577, relative error 0.31542.
:large_orange_diamond: Flowthrough_x_inflow_y_outflow_acc: Nonzero diffs: `fg_e_2` has absolute error 0.000374883, relative error 0.0749812.
:large_orange_diamond: Flowthrough_amr: Nonzero diffs: `proton/vg_rho_0` has absolute error 6868.4, relative error 0.00318262.
:large_orange_diamond: Magnetosphere_3D_small: Nonzero diffs: `proton/vg_v_0` has absolute error 905.686, relative error 0.00120719.
:large_orange_diamond: Ionosphere_small: Nonzero diffs: `proton/vg_v_0` has absolute error 455.535, relative error 0.000607185.

Full testpackage run output is available in `/home/uganse/work/testpackage/testpackage_run_ad7155c8cfef9ec0194701dd105084a14cfbccc6.log` on host `turso01.cs.helsinki.fi`

**Comment by ursg** [comment]
Hmpf, ok, so I guess this test shows that I have to still grind my teeth on that script a bit...

**Comment by ursg** [comment]
Ok, this was stupid. The magnetosphere_polar_small failed to run because
```
what():  unrecognised option 'gridbuilder.timeclass_max'
```
(Because I had *just* plonked that in there to produce a figure for the timeclass presentation).

**Comment by ursg** [comment]
Automatic testpackage output for pull request #676.

Based on commit f669274c03d05574e312fa21c2b21b2c993efb2e.

Process started by user ```uganse``` on host ```turso01.cs.helsinki.fi``` at Wed, 14 Dec 2022 14:24:15 +0200.

:heavy_check_mark: Compilation succeeded with 29 warnings.

:heavy_check_mark: Testpackage ran successfully.

:large_orange_diamond: acctest_2_maxw_500k_100k_20kms_10deg: Nonzero diffs: `proton/vg_v_0` has absolute error 17.2056, relative error 0.123849.
:large_orange_diamond: acctest_3_substeps: Nonzero diffs: `proton/vg_rho_0` has absolute error 31.6293, relative error 7.90719e-06.
:large_orange_diamond: transtest_2_maxw_500k_100k_20kms_20x20: Nonzero diffs: `proton/vg_rho_0` has absolute error 0.0652471, relative error 6.52505e-08.
:heavy_check_mark: acctest_4_helium: Zero diffs.
:large_orange_diamond: acctest_5_proton_antiproton: Nonzero diffs: `proton/vg_rho_0` has absolute error 1.20169, relative error 3.00418e-07.
:large_orange_diamond: restart_write: Nonzero diffs: `proton/vg_rho_0` has absolute error 0.237268, relative error 2.37335e-07.
:large_orange_diamond: restart_read: Nonzero diffs: `proton/vg_rho_0` has absolute error 0.237268, relative error 2.37335e-07.
:large_orange_diamond: Magnetosphere_small: Nonzero diffs: `proton/vg_v_0` has absolute error 33.0774, relative error 6.5597e-05.
:large_orange_diamond: Magnetosphere_polar_small: Nonzero diffs: `proton/vg_v_nonthermal_0` has absolute error 23967.1, relative error 0.0299727.
:large_orange_diamond: test_fp_fsolver_only_3D: Nonzero diffs: `fg_e_0` has absolute error 4.76587e-11, relative error 2.75134e-05.
:large_orange_diamond: test_fp_substeps: Nonzero diffs: `fg_e_0` has absolute error 5.27205e-11, relative error 3.03704e-05.
:large_orange_diamond: Flowthrough_trans_periodic: Nonzero diffs: `proton/vg_v_0` has absolute error 460.27, relative error 0.000927346.
:large_orange_diamond: Flowthrough_x_inflow_y_outflow: Nonzero diffs: `proton/vg_rho_0` has absolute error 0.0951692, relative error 9.5196e-08.
:large_orange_diamond: Flowthrough_x_inflow_y_outflow_acc: Nonzero diffs: `proton/vg_rho_0` has absolute error 213.374, relative error 0.000101996.
:large_orange_diamond: Flowthrough_amr: Nonzero diffs: `proton/vg_rho_0` has absolute error 144.992, relative error 6.72144e-05.
:large_orange_diamond: Magnetosphere_3D_small: Nonzero diffs: `proton/vg_v_2` has absolute error 5.26346, relative error 0.0119977.
:red_circle: Ionosphere_small: Failed to run or died with an error.

Full testpackage run output is available in `/home/uganse/work/testpackage/testpackage_run_f669274c03d05574e312fa21c2b21b2c993efb2e.log` on host `turso01.cs.helsinki.fi`

**Comment by ursg** [comment]
Now, with the automatic testing finally in place, this also produces green checks and only the typical numerics-level diffs of the testpackage. So no reason to keep holding it off!

**Pull request merged**
