### PR TITLE
Cache neighbors

### PR DESCRIPTION
**Pull request by lkotipal**
Always use const references to face neighbors.

Goes together with https://github.com/fmihpc/dccrg/pull/24.

### CODE REVIEW

**Comment by lkotipal** [comment]
Please open a thread for me GithubBot!

**Comment by lkotipal** [comment]
Automatic testpackage output for pull request #717.

Based on commit e4cab828e77515b24820cd8978cf2309a28d2aea.

Process started by user ```lkotipal``` on host ```turso03.cs.helsinki.fi``` at Fri, 10 Mar 2023 19:42:27 +0200.

:heavy_check_mark: Compilation succeeded with 27 warnings.

:heavy_check_mark: Testpackage ran successfully.

:red_circle: acctest_2_maxw_500k_100k_20kms_10deg: Failed to run or died with an error.
:red_circle: acctest_3_substeps: Failed to run or died with an error.
:red_circle: transtest_2_maxw_500k_100k_20kms_20x20: Failed to run or died with an error.
:red_circle: acctest_4_helium: Failed to run or died with an error.
:red_circle: acctest_5_proton_antiproton: Failed to run or died with an error.
:red_circle: restart_write: Failed to run or died with an error.
:red_circle: restart_read: Failed to run or died with an error.
:red_circle: Magnetosphere_small: Failed to run or died with an error.
:red_circle: Magnetosphere_polar_small: Failed to run or died with an error.
:red_circle: test_fp_fsolver_only_3D: Failed to run or died with an error.
:red_circle: test_fp_substeps: Failed to run or died with an error.
:red_circle: Flowthrough_trans_periodic: Failed to run or died with an error.
:red_circle: Flowthrough_x_inflow_y_outflow: Failed to run or died with an error.
:red_circle: Flowthrough_x_inflow_y_outflow_acc: Failed to run or died with an error.
:red_circle: Flowthrough_amr: Failed to run or died with an error.
:red_circle: Magnetosphere_3D_small: Failed to run or died with an error.
:red_circle: Ionosphere_small: Failed to run or died with an error.

Full testpackage run output is available in `/wrk-vakka/users/lkotipal/testpackage/testpackage_run_e4cab828e77515b24820cd8978cf2309a28d2aea.log` on host `turso03.cs.helsinki.fi`

**Comment by lkotipal** [comment]
Automatic testpackage output for pull request #717.

Based on commit e4cab828e77515b24820cd8978cf2309a28d2aea.

Process started by user ```lkotipal``` on host ```turso03.cs.helsinki.fi``` at Fri, 10 Mar 2023 19:54:18 +0200.

:heavy_check_mark: Compilation succeeded with 27 warnings.

:heavy_check_mark: Testpackage ran successfully.

:heavy_check_mark: acctest_2_maxw_500k_100k_20kms_10deg: Zero diffs.
:heavy_check_mark: acctest_3_substeps: Zero diffs.
:heavy_check_mark: transtest_2_maxw_500k_100k_20kms_20x20: Zero diffs.
:heavy_check_mark: acctest_4_helium: Zero diffs.
:heavy_check_mark: acctest_5_proton_antiproton: Zero diffs.
:heavy_check_mark: restart_write: Zero diffs.
:heavy_check_mark: restart_read: Zero diffs.
:heavy_check_mark: Magnetosphere_small: Zero diffs.
:heavy_check_mark: Magnetosphere_polar_small: Zero diffs.
:heavy_check_mark: test_fp_fsolver_only_3D: Zero diffs.
:heavy_check_mark: test_fp_substeps: Zero diffs.
:heavy_check_mark: Flowthrough_trans_periodic: Zero diffs.
:heavy_check_mark: Flowthrough_x_inflow_y_outflow: Zero diffs.
:heavy_check_mark: Flowthrough_x_inflow_y_outflow_acc: Zero diffs.
:heavy_check_mark: Flowthrough_amr: Zero diffs.
:heavy_check_mark: Magnetosphere_3D_small: Zero diffs.
:heavy_check_mark: Ionosphere_small: Zero diffs.

Full testpackage run output is available in `/wrk-vakka/users/lkotipal/testpackage/testpackage_run_e4cab828e77515b24820cd8978cf2309a28d2aea.log` on host `turso03.cs.helsinki.fi`

**Comment by lkotipal** [comment]
Speedups on CI seem completely unreliable, and the output from the automatic testpackage doesn't seem to show any improvement. This might be a dead end.

**Comment by lkotipal** [comment]
Running a single node ionosphere test on Lumi and a 10s EGI_like on Mahti I'm getting a ~5% speedup, so this actually seems like a great improvement.

**Comment by lkotipal** [comment]
20s of Magnetosphere3D on Lumi gives similar results.

**Comment by markusbattarbee** [comment]
Great - can we please have relevant excerpts from the phiprof outputs as well? What task/node/thread balances did you use?

**Comment by lkotipal** [comment]
The relevant part of the job script on Lumi:
```
#SBATCH --partition=standard
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=16
#SBATCH --hint=multithread
```

As for profiling output, here's the top level timer and propagate for the Lumi runs:
```
-------------------------------------------------------------------------------------------------------
  %Total Time       Exclusive         Inclusive        #Calls  #Child Calls       Inclusive/Call   Name
-------------------------------------------------------------------------------------------------------
        100.0           0.002          1669.378             1         1.493             1669.378   .TAU application (control)
         11.8           0.002           196.269        47.118       327.287                4.166   Propagate (control)
-------------------------------------------------------------------------------------------------------
        100.0           0.002           1589.78             1         1.483              1589.78   .TAU application
         11.9           0.002           189.821        47.118       327.304                4.029   Propagate (cached)
```
Showing 4.8% and 3.3% speedups.

**Comment by markusbattarbee** [comment]
and what about the interim region `translate proton`, the x-y-z specific `compute-mapping-x` and `update_remote-x` regions? Under ` <= semilag-trans <= Spatial-space <= Propagate <= Simulation <= main <= taupreload_main <= .TAU application`

**Comment by lkotipal** [comment]
And here are all timers that take at least 0.1% of total time.
[cached.txt](https://github.com/fmihpc/vlasiator/files/11232054/cached.txt)
[control.txt](https://github.com/fmihpc/vlasiator/files/11232055/control.txt)

**Comment by markusbattarbee** [comment]
Thank you, looks good to me. I guess the way we should do this is first merge the DCCRG PR, update the centrally maintained dccrg versions on e.g. carrington, mahti, lumi etc, and then edit this PR to walk back the changes to the CI runner and the Carrington makefile?

**Review by markusbattarbee — APPROVED** [review]

**Comment by ykempf** [comment]
OK by me too, I'll let @ursg do this so the DCCRG is also done at the same time and he can update it for the CI.

**Comment by markusbattarbee** [comment]
Since Leo already reverted this to not depend on the DCCRG PR, we can just merge this straight away. When the DCCRG PR is also merged, it will benefit from that speed increase.

**Pull request merged**
