### PR TITLE
Specify port in transferPraceData if needed.

### PR DESCRIPTION
**Pull request by ykempf**

### CODE REVIEW

**Comment by ykempf** [comment]
No, it copies to HazelHen...

**Comment by markusbattarbee** [comment]
nitpick: you can't actually specify the port, contrary to what the commit description says :) But if that hardcoded port is ok then I guess it's ok

**Comment by ykempf** [comment]
Well you have to declare 1235 going to taito when ssh'ing to HazelHen. If you want another port, it has to be changed in the script. I won't change the commit message though. ;)

**Comment by ursg** [comment]
Alrighty, no reason not to merge this!

**Pull request merged**
