### PR TITLE
Restructured OpenACC acceleration solver to parallelize over columns.

### PR DESCRIPTION
**Pull request by ursg**
It's faster! And it doesn't seem to be all wrong (at first glance).

### CODE REVIEW

**Comment by ursg** [comment]
Actually, under closer inspection, this does still seem to have at least one bug. After acceleration, everything seems to be off by one velocity block in some direction (here are pictures of the first three timesteps):




I'll go through the old and new version of the code and check what I have messed up here.

**Comment by ykempf** [comment]
Let's make a simple test like the original test_acc. That'll be more informative than Magnetosphere.

On 20 October 2019 16:03:54 EEST, Urs Ganse <notifications@github.com> wrote:
>Actually, under closer inspection, this does still seem to have at
>least one bug. After acceleration, everything seems to be off by one
>velocity block in some direction (here are pictures of the first three
>timesteps):
>
>
>
>
>I'll go through the old and new version of the code and check what I
>have messed up here.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fmihpc/vlasiator/pull/448#issuecomment-544250373

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ursg** [comment]
Alright, I ran with a acctest_1, where I disabled all acceleration directions apart from x, and see what it does:







So this looks to me like it's having maybe two distinct problems? One being that old velocity space memory contents don't get cleared and just linger around and the other one being that *some* columns don't move the way they should.

**Comment by ykempf** [comment]
T0 is already looking weird to me. Is there no test_acc anymore?

**Comment by ursg** [comment]
Do you mean projects/unsupported/test_acc?

**Comment by ykempf** [comment]
Apparently I do. :)

**Comment by ursg** [comment]
Ok, the last commit seems to have fixed it, the columns are no longer swooshing away in velocity space:

**Pull request merged**
