### PR TITLE
Add phiprof::stop to early return calls.

### PR DESCRIPTION
**Pull request by ykempf**

### CODE REVIEW

**Comment by ursg** [comment]
Wow, that's actually a lot of them! Thumbs up!

**Comment by ykempf** [comment]
Hmm until other spots bite us when TAUing – should someone go through systematically? Can we make that automatic? Probably not?

**Comment by ursg** [comment]
#721 of makes the type system take care of this for us. So maybe no need to manually go through everything anymore?

**Comment by ykempf** [comment]
True. Great!

**Pull request merged**
