### PR TITLE
Additional implementations and debugging for FALLBACK support. Tested…

### PR DESCRIPTION
**Pull request by ykempf**
… on Hawk.

### CODE REVIEW

**Comment by ykempf** [comment]
Consistency of 4D vs 8F in Magnetosphere_polar_small:

```
$ ./vlsvdiff_DP *FALLBACK/bulk.0000000.vlsv proton/vg_rho 0 | head -n 5                                                                                                                                                                                                                                     
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
The absolute 0-distance between both datasets is 0.0115808
The relative 0-distance between both datasets is 1.15808e-08

$ ./vlsvdiff_DP *AGNER/bulk.0000001.vlsv proton/vg_rho 0 | head -n 5                                                                                                                                                                                                                                        
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.91
The absolute 0-distance between both datasets is 8.43216
The relative 0-distance between both datasets is 5.38077e-06

$ ./vlsvdiff_DP *FALLBACK/bulk.0000001.vlsv proton/vg_rho 0 | head -n 5                                                                                                                                                                                                                                     
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.91
The absolute 0-distance between both datasets is 7.90017
The relative 0-distance between both datasets is 5.04129e-06
```

**Comment by ykempf** [comment]
Consistency of AGNER vs FALLBACK in Magnetosphere_polar_small:
```
./vlsvdiff_DP 4D*/bulk.0000000.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
The absolute 0-distance between both datasets is 0
The relative 0-distance between both datasets is 0
s32846 login2 720$ ./vlsvdiff_DP 8F*/bulk.0000000.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
The absolute 0-distance between both datasets is 0
The relative 0-distance between both datasets is 0
s32846 login2 721$ ./vlsvdiff_DP 4D*/bulk.0000001.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
The absolute 0-distance between both datasets is 0.0841234
The relative 0-distance between both datasets is 5.36812e-08
s32846 login2 722$ ./vlsvdiff_DP 8F*/bulk.0000001.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.91
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.91
The absolute 0-distance between both datasets is 8.5818
The relative 0-distance between both datasets is 5.47628e-06
```

**Comment by ykempf** [comment]
I'll rerun the FALLBACK tests after this merge fix.

**Comment by ykempf** [comment]
Same results.

**Comment by ykempf** [comment]
4D vs 8D FALLBACK in Magnetosphere_polar_small:
```
$ ./vlsvdiff_DP {4,8}D_FALLBACK/bulk.0000000.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
The absolute 0-distance between both datasets is 0
The relative 0-distance between both datasets is 0

$ ./vlsvdiff_DP {4,8}D_FALLBACK/bulk.0000001.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
The absolute 0-distance between both datasets is 1.03886
The relative 0-distance between both datasets is 6.62924e-07
```

**Comment by ykempf** [comment]
8F vs 8D FALLBACK, same test:
```
$ ./vlsvdiff_DP 8[FD]_FALLBACK/bulk.0000000.vlsv proton/vg_rho 0 | head -n 5                                                                                                                                                                                                                                
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
Statistics on file: size 3150 min = 0 max = 1e+06 average = 994286 standard deviation 1343.44
The absolute 0-distance between both datasets is 0.0115808
The relative 0-distance between both datasets is 1.15808e-08

$ ./vlsvdiff_DP 8[FD]_FALLBACK/bulk.0000001.vlsv proton/vg_rho 0 | head -n 5
INFO Reading in two files.
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.92
Statistics on file: size 3150 min = 0 max = 1.56709e+06 average = 994169 standard deviation 1731.91
The absolute 0-distance between both datasets is 7.90017
The relative 0-distance between both datasets is 5.04129e-06
```

**Review by markusbattarbee — APPROVED** [review]
gud

**Review by ursg — APPROVED** [review]
Looks good. Seems to work well. What is there not to like. :)

**Pull request merged**
