### PR TITLE
Fix check cfg output variables

### PR DESCRIPTION
**Pull request by ykempf**
Keep fixing that script. Don't merge yet, there's one outstanding problem I'll fix next week or so.

### CODE REVIEW

**Comment by ykempf** [comment]
Not to myself: Fix the lines with "opt_protected" to cover all the characters in <population>_sparse.dynamicAlgorithm.

**Comment by ykempf** [comment]
Also: comment the bash magic.

**Comment by ykempf** [comment]
This commit protects the asterisk in population lines and now <population>_sparse.dynamicAlgorithm is displayed properly as an unused option.

**Comment by ykempf** [comment]
And here are some more comments.

**Comment by ykempf** [comment]
@ursg @tkoskela I added another feature, the script now tells also when the variable list was updated. Please test the script again and report if you see anything suspicious.

**Comment by ykempf** [comment]
I have, with a testpackage config. Have you tested? It's always good to test on different systems...

**Comment by markusbattarbee** [comment]
taperradius and dynamic are set for the per-pop boundaries:

[ionosphere]
centerX = 0.0
centerY = 0.0
centerZ = 0.0
radius = 31.8e6
precedence = 2

[proton_ionosphere]
rho = 1.0e6
VX0 = 0.0
VY0 = 0.0
VZ0 = 0.0
taperRadius = 1.0e8

[maxwellian]
face = x+
precedence = 4

[proton_maxwellian]
dynamic = 0
file_x+ = sw1.dat

**Comment by ykempf** [comment]
But please do report inconsistencies, as I might well still have bugs...

**Comment by ykempf** [comment]
Like so @tkoskela?

**Pull request merged**
