### PR TITLE
Fix to vlsvextract because of erroneous loop over meshes.

### PR DESCRIPTION
**Pull request by ykempf**

### CODE REVIEW

**Comment by ykempf** [comment]
Wait

**Comment by ykempf** [comment]
Nyt

**Comment by ursg** [comment]
I suppose that breaks the old vAMR stuff that Arto wrote a long time ago, but that's ok, since there's no intention to use that anyway. So by and large, I'd say it looks good.

**Comment by markusbattarbee** [comment]
Looks ok to me too.

**Pull request merged**
