### PR TITLE
Dev fix ionosphere

### PR DESCRIPTION
**Pull request by ykempf**
Any comments?

### CODE REVIEW

**Comment by ursg** [comment]
Uh, is this still reasonably fast? Doesn't this potentially cause the layer identification loop to go from being evaluated 3 times to being evaluated multiple thousands of times?

Maybe we can early-exit that loop, if no more cells will be tagged as the next layers?

**Comment by ykempf** [comment]
Nah. Let's do one pass over all cells setting the layer. Then a second classic pass, as is done above with DCCRG.

**Comment by ykempf** [comment]
BRB

**Comment by ykempf** [comment]
Oh nooo, something is tangled in my git now apparently...

**Comment by ykempf** [comment]
This looks better now... Doesn't it?

**Comment by tkoskela** [comment]
Looks good to me

**Comment by ykempf** [comment]
With the last commit this allows the testpackage tests to all run. Actual checking against another version fails for all E and B comparisons and there seems to be multipop issues too, but at least the runs go through.

**Pull request merged**
