### PR TITLE
Egi monstermerge

### PR DESCRIPTION
**Pull request by ursg**
This is the amalgamation of a big number of loose branches that we pull together for the next big 3D simulation ("EGI"):

- [x] https://github.com/markusbattarbee/vlasiator-public/tree/dccrg_update2
- [x] https://github.com/fmihpc/vlasiator/pull/507
- [x] https://github.com/fmihpc/vlasiator/pull/491 (plus a small dirty fix for crashes, that might still be overriden)
- [x] https://github.com/fmihpc/vlasiator/pull/485
- [x] https://github.com/fmihpc/vlasiator/pull/484
- [x] https://github.com/markusbattarbee/vlasiator-public/pull/9
- [x] https://github.com/ursg/vlasiator/tree/ionosphere
- [x] Vlsvdiff updates from https://github.com/kstppd/vlasiator/tree/vlsvTools

Still Missing:
- [ ] Bulirsch-Stoer fixes for ionosphere stepping

Current state of this is that it compiles, and will still need to be tested before it gets green light to go.

### CODE REVIEW

**Comment by markusbattarbee** [comment]
The vector calculations in sphericaltrigrid do not compile with FALLBACK

**Comment by markusbattarbee** [comment]
With agner too I get errors from not having support for Vec3Dd
What's this?

**Comment by ykempf** [comment]
I got it compiled and running on Hawk, was there some changes to Makefiles?

**Comment by markusbattarbee** [comment]
Ah-ha, the old version1 of vectorclass and it's add-on both needed to be updated.
Still, this means that the ionosphere won't compile with FALLBACK so merging into dev will cause problems with our openacc branch.

**Comment by ursg** [comment]
Superseded by #512

**Pull request closed without merging**
