### PR TITLE
Added two openmp for loops in LB weight assignment.

### PR DESCRIPTION
**Pull request by ykempf**
I want to see what the testpackage makes of this. CI FTV.

### CODE REVIEW

**Comment by ykempf** [comment]
So was speedup supposed to be <1 or >1?

**Comment by lkotipal** [comment]
Speedup > 1 is faster. The CI testpackage seems unreliable for measuring speedup, however.

**Comment by markusbattarbee** [comment]
I wouldn't expect any actual benefit here, but indeed why not.

**Comment by lkotipal** [comment]
Might need a more robust performance measurement to be helpful. It's fairly straightforward to run the testpackage through `tau_exec`. Maybe we should look into using tau tools to automate the processing of performance data?

**Comment by ursg** [comment]
Yup.

**Pull request merged**
