### PR TITLE
Update velocity space neighbour information correctly so that outflow…

### PR DESCRIPTION
**Pull request by ykempf**
… has the correct info.

### CODE REVIEW

**Comment by ykempf** [comment]
Yeepee, number 500! ...and I could walk 500 more...

**Review by ursg — APPROVED** [review]
Code looks good, but I didn't quite get: what was the corner case where the extended neighbourhood was required for this?

**Comment by ykempf** [comment]
If a layer 2 outflow cell has the layer 2 inner cell to copy from remotely on another process, this failed. It was easiest to demonstrate with a RANDOM load balancing.

On 6 September 2020 21:28:20 EEST, Urs Ganse <notifications@github.com> wrote:
>@ursg approved this pull request.
>
>Code looks good, but I didn't quite get: what was the corner case where
>the extended neighbourhood was required for this?
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fmihpc/vlasiator/pull/500#pullrequestreview-483163922

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ursg** [comment]
Right-o. Let's merge it!

**Pull request merged**
