### PR TITLE
Cudasiator

### PR DESCRIPTION
**Pull request by markusbattarbee**
Brings Cudasiator up to date with dev; also removes old spatial_mesh constructs and switches the ionosphere and fieldtracer routines to use Eigen instead of vectorclass.

### CODE REVIEW

**Comment by ursg** [comment]
Way too big a diff to scroll through all of it, but I'm conceptually approving that everything goes up to date.

**Comment by markusbattarbee** [comment]
Tested that the CUDA version compiles and runs. Made this into a PR instead of directly merging so @hokkanen can see if it breaks things for him

**Comment by ursg** [comment]
Does this now need a rebase, now that #686, #668 and #678 are merged in dev? Or should it keep going as such?

**Comment by markusbattarbee** [comment]
Ho hum. Yeah I think I'll need to do that, and it might be a bit messy as some of those changes were include here, but not necessarily always from the same commit.

**Pull request closed without merging**
